export const VALIDATE_COUPON_REQUEST = "VALIDATE_COUPON_REQUEST"
export const VALIDATE_COUPON_SUCCESS = "VALIDATE_COUPON_SUCCESS"
export const VALIDATE_COUPON_FAIL = "VALIDATE_COUPON_FAIL"

export const RESET_COUPON = "RESET_COUPON"

export const CLEAR_ERRORS = "CLEAR_ERRORS"