export const MY_ORDERS_REQUEST = "MY_ORDERS_REQUEST"
export const MY_ORDERS_SUCCESS = "MY_ORDERS_SUCCESS"
export const MY_ORDERS_FAIL = "MY_ORDERS_FAIL"

export const PLACE_NEW_ORDER_REQUEST= "PLACE_NEW_ORDER_REQUEST"
export const PLACE_NEW_ORDER_SUCCESS= "PLACE_NEW_ORDER_SUCCESS"
export const PLACE_NEW_ORDER_FAIL = "PLACE_NEW_ORDER_FAIL"

export const RESET_NEW_ORDER = "RESET_NEW_ORDER"

export const CLEAR_ERRORS = "CLEAR_ERRORS"