export const TRENDNIG_PRODUCTS_REQUEST = "TRENDNIG_PRODUCTS_REQUEST"
export const TRENDNIG_PRODUCTS_SUCCESS = "TRENDNIG_PRODUCTS_SUCCESS"
export const TRENDNIG_PRODUCTS_FAIL = "TRENDNIG_PRODUCTS_FAIL"

export const FAVOURITE_PRODUCTS_REQUEST = "FAVOURITE_PRODUCTS_REQUEST"
export const FAVOURITE_PRODUCTS_SUCCESS = "FAVOURITE_PRODUCTS_SUCCESS"
export const FAVOURITE_PRODUCTS_FAIL = "FAVOURITE_PRODUCTS_FAIL"

export const MOST_ORDERED_PRODUCTS_REQUEST = "MOST_ORDERED_PRODUCTS_REQUEST"
export const MOST_ORDERED_PRODUCTS_SUCCESS = "MOST_ORDERED_PRODUCTS_SUCCESS"
export const MOST_ORDERED_PRODUCTS_FAIL = "MOST_ORDERED_PRODUCTS_FAIL"

export const SUGGESTED_PRODUCTS_REQUEST = "SUGGESTED_PRODUCTS_REQUEST"
export const SUGGESTED_PRODUCTS_SUCCESS = "SUGGESTED_PRODUCTS_SUCCESS"
export const SUGGESTED_PRODUCTS_FAIL = "SUGGESTED_PRODUCTS_FAIL"

export const ALL_PRODUCT_REQUEST = "ALL_PRODUCT_REQUEST"
export const ALL_PRODUCT_SUCCESS = "ALL_PRODUCT_SUCCESS"
export const ALL_PRODUCT_FAIL = "ALL_PRODUCT_FAIL"

export const PRODUCT_BY_CATEGORY_REQUEST = "PRODUCT_BY_CATEGORY_REQUEST"
export const PRODUCT_BY_CATEGORY_SUCCESS = "PRODUCT_BY_CATEGORY_SUCCESS"
export const PRODUCT_BY_CATEGORY_FAIL = "PRODUCT_BY_CATEGORY_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"