export const SEND_LOGIN_OTP_REQUEST = "SEND_LOGIN_OTP_REQUEST"
export const SEND_LOGIN_OTP_SUCCESS = "SEND_LOGIN_OTP_SUCCESS"
export const SEND_LOGIN_OTP_FAIL = "SEND_LOGIN_OTP_FAIL"

export const LOGIN_VIA_OTP_REQUEST = "LOGIN_VIA_OTP_REQUEST"
export const LOGIN_VIA_OTP_SUCCESS = "LOGIN_VIA_OTP_SUCCESS"
export const LOGIN_VIA_OTP_FAIL = "LOGIN_VIA_OTP_FAIL"

export const SEND_SIGNUP_OTP_REQUEST = "SEND_SIGNUP_OTP_REQUEST"
export const SEND_SIGNUP_OTP_SUCCESS = "SEND_SIGNUP_OTP_SUCCESS"
export const SEND_SIGNUP_OTP_FAIL = "SEND_SIGNUP_OTP_FAIL"

export const VERIFY_SIGNUP_VIA_OTP_REQUEST = "VERIFY_SIGNUP_VIA_OTP_REQUEST"
export const VERIFY_SIGNUP_VIA_OTP_SUCCESS = "VERIFY_SIGNUP_VIA_OTP_SUCCESS"
export const VERIFY_SIGNUP_VIA_OTP_FAIL = "VERIFY_SIGNUP_VIA_OTP_FAIL"

export const SIGNUP_VIA_OTP_REQUEST = "SIGNUP_VIA_OTP_REQUEST"
export const SIGNUP_VIA_OTP_SUCCESS = "SIGNUP_VIA_OTP_SUCCESS"
export const SIGNUP_VIA_OTP_FAIL = "SIGNUP_VIA_OTP_FAIL"

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
export const LOGOUT_FAIL = "LOGOUT_FAIL"




// this gives info of myself
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

// Update User Details
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS= "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_RESET = "UPDATE_USER_RESET"

export const CLEAR_ERRORS = "CLEAR_ERRORS"